FROM node:18-alpine

RUN apk add python3 py3-pip gfortran musl-dev gcc
RUN apk add py3-pandas py3-numpy
RUN apk add py3-pytest
RUN npm install -g pyright

WORKDIR /workspace

RUN mkdir -p /workspace

ENTRYPOINT []
CMD []