version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: sc-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: sc-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  rdbms:
    image: postgres:14.1-alpine
    container_name: sc-rdbms
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - rdbms:/var/lib/postgresql/data
      - ./init-rdb:/docker-entrypoint-initdb.d

#  flyway:
#    image: redgate/flyway:latest
#    container_name: sc-flyway
#    command:
#      - "-url=jdbc:postgresql://rdbms/supreme_code"
#      - "-user=supreme_user"
#      - "-password=password"
#      - "-schemas=supreme_code"
#    depends_on:
#      - rdbms
#    volumes:
#      - ./web/src/main/resources/db/migration
volumes:
  rdbms:
    driver: local