version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: sc-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: sc-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  rdbms:
    image: postgres:14.1-alpine
    container_name: sc-rdbms
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - rdbms:/var/lib/postgresql/data
      - ./init-rdb:/docker-entrypoint-initdb.d

volumes:
  rdbms:
    driver: local