spring:
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://localhost/supreme_code
    username: supreme_user
    password: password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: web-group

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: supreme_code
    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQL14Dialect
  flyway:
    url: jdbc:postgresql://localhost/supreme_code
    user: supreme_user
    password: password
    default-schema: supreme_code

supreme-code:
  content-repository:
    path: /supreme-code-content/content
    problem:
      path: /supreme-code-content/content/problems