spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: web-group

  r2dbc:
    url: r2dbc:postgresql://localhost/supreme_code
    username: supreme_user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    url: jdbc:postgresql://localhost/supreme_code
    user: supreme_user
    password: password
    default-schema: supreme_code
