spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:postgresql://localhost/supreme_code
    username: supreme_user
    password: password
    properties:
      sslMode: DISABLED

  datasource:
    url: jdbc:postgresql://localhost/supreme_code
    username: supreme_user
    password: password
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: web-group

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: supreme_code
    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQL14Dialect
  flyway:
    url: jdbc:postgresql://localhost/supreme_code
    user: supreme_user
    password: password
    default-schema: supreme_code
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
supreme-code:
  content-repository:
    path: /supreme-code-content/content
    problem:
      path: /supreme-code-content/content/problems

jwt:
  cookie-name: sc-token
  password:
    encoder:
      secret: oZr417KU7ipPoCCGY0-cPcGu0PpT1_aG9o-BD1KcnN3BpZPrLcNKgcF9QXXJwrY50Whd7Ij51t45oD0ctn-Vo032uFoMtnNzvzpOFq
      iteration: 33
      keylength: 256
  secret: AMDXGbO7gGwf3hoFPpm6GwQvFrqoCsn2 #This Secret For JWT HS256 Signature Algorithm MUST Have 256 bits KeySize
  expiration: 28800 # token expiration in seconds