spring:
  application:
    name: test-runner

server:
  port: 8091

supreme-code:
  test-runner:
    container:
      ttk: 12000

minio:
  url: http://localhost:9000
  access-key: minio
  secret-key: minio123
  bucket: my-bucket

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics, info
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  pattern:
    level: "%5p [%X{trace_id:-},%X{span_id:-}]"
