supreme-code:
  content-repository:
    root: C:\Users\Danil\IdeaProjects\supreme-code\supreme-code-content
    path: /content
    problem:
      path: /content/problems
  test-runner:
    container:
      ttk: 12000
logging:
  level:
    net:
      danil: debug
    org:
      danil: debug