supreme-code:
  content-repository:
    path: supreme-code-content/content
    problem:
      path: supreme-code-content/content/problems
  test-runner:
    container:
      ttk: 4000
logging:
  level:
    net:
      danil: debug
    org:
      danil: debug